### ISSUE TITLE
Request: add BORGSWAP.Exchange

### ISSUE THREAD

**Issue by locutusofborg111** [VenusProtocol/bsctokenlists-org#7]
Checklist
- [X] **I understand that this is not the place to request token listing.**
- [X] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.venus.io`.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List URL: https://api.borgswap.exchange/tokens.json
List Name: BORGSWAP.Exchange
Link to the official homepage of the list manager: https://borgswap.exchange

**Comment by gryincent** [comment]
please create PR to add your list

**Comment by gryincent** [comment]
merged
